#!/bin/bash

#------------------------------------------------------------------------------
#  LOrkNetLib - Laptop Orchestra Network Library Toolkit
#
#  Copyright (c) 2010 Mark Cerqueira and Dan Trueman.  All rights reserved.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
#  U.S.A.
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# name: client.sh
# desc: this program runs client programs to listen for, receive, and log
# packets received sent from servers
#
# to run (in command line python):
#     %> ./client.sh num_LOrktops num_servers
#
# NOTE: run client.sh with server.sh and parent.sh scripts
#------------------------------------------------------------------------------

# script needs to be passed the number of LOrktops running the scripts and 
# number of servers running scripts
if [ $# -ne 2 ];
then
    echo "Usage: clientsh num_LOrktops num_servers"
    exit 65
fi

# update this array to include the NET_NAME of all PLOrktops you are going
# to be using in order - to make your life easier just use the build.py script!

